'use strict'
'require form'

return L.view.extend({
  load: function () {

  },
  render: function () {

    try {
      document.head.appendChild(E('link', {
        'rel': 'stylesheet',
        'href': '/luci-static/resources/view/rpnd/rpnd.css'
      }))
    } catch (e) { }

    var m, s, o
    m = new form.Map('rpnd', _('Configuration'), _('IOT comunications'))

    s = m.section(form.TypedSection, 'mqtt', _('Mqtt'))
    s.anonymous = true
    s.addremove = false

    o = s.option(form.Value, 'url', _('Server url'), _('Mqtt server url'))
    o.placeholder = 'mqtt[s]://host.domain[:port]'
    o.datatype = 'string'

    o = s.option(form.Value, 'username', _('User Name'), _('User with write access for configured topics'))
    o.datatype = 'string'

    o = s.option(form.Value, 'password', _('Password'), _(''))
    o.datatype = 'string'
    o.password = true

    o = s.option(form.Value, 'client_id', _('Client ID'), _('Client ids must be unique on server. <br/> Empty for autogenerated'))
    o.optional = true
    o.datatype = 'string'
    o.placeholder = 'NodeName-NodeId'

    o = s.option(form.Value, 'status_topic', _('Status Topic'), _('Module status changes are published to this topic'))
    o.optional = true
    o.datatype = 'string'

    return m.render()
  }
})
